### ISSUE TITLE
0 does not evaluate to 'falsey' in Ruby

### ISSUE THREAD

**Issue by mendelB** [learn-co-curriculum/login_required_readme#4]
The Readme says

> We're using the phrase `unless session.include?` rather than `unless session[:user_id]`, because a user_id of 0 is still a valid user id, but would evaluate falsey, and reject the request.

In Ruby the Integer `0` does not evaluate to 'falsey' and `unless session[:user_id]` would indeed be a valid way to check for the user id.

http://stackoverflow.com/a/23068894/5657278
https://www.codecademy.com/en/forum_questions/5066722a8fd3f20002013b82
http://stackoverflow.com/questions/10387515/why-treat-0-as-true-in-ruby

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
