### ISSUE TITLE
The 'Login Required README/Lab Pair seems to be too early

### ISSUE THREAD

**Issue by mendelB** [learn-co-curriculum/login_required_readme#5]
This Readme seems to assume some prior knowledge about logging in a user using the session. And while we have covered this in Sinata and indeed the readme makes vague reference to "...as we saw in the last section..." going forward to the Lab it makes many assumptions about concepts that are clearly explained in the next Redme/Lab pair: 'Sessions Controller'. (One great example being the first instruction of the lab "Build out the SessionsController." this is exactly what is taught in the aptly names `Sessions Controller` Readme/lab pair :)

Making the switch and putting this pair after the 'sessions controller' pair would definitely clarify things and make sense in how the concepts are presented.

This is mentioned in https://github.com/learn-co-curriculum/login_required_lab/issues/15

@AnnJohn @PeterBell

**Comment by mendelB** [comment]
It seems @jmburges addressed this issue here:
https://github.com/learn-co-curriculum/sessions_controller_readme/issues/2

I still maintain that the content of these readmes and labs really seems to fit more with the opposite order. While we do cover sessions in Sinatra and they should know how to wire that together at this point, the way the buildup is done in this section and just the way the readmes are worded really seem much more natural with the opposite order and slightly confusing the way it is.  
(It seems that the Login lab/readme covers authentication based on the login system and sessions builds out the login system to begin with)

I'd love your thoughts on this Joe!

**Comment by mendelB** [comment]
Hey @jmburges Would you be able to make a call on this one? (This would close out a number of issues)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated and reordered the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
