### ISSUE TITLE
Deprecation warning when running secrets_controller_spec.rb

### ISSUE THREAD

**Issue by aminamos** [learn-co-curriculum/login_required_readme#6]
"DEPRECATION WARNING: Using positional arguments in functional tests has been deprecated,
in favor of keyword arguments, and will be removed in Rails 5.1.

Deprecated style:
get :show, { id: 1 }, nil, { notice: "This is a flash message" }

New keyword style:
get :show, params: { id: 1 }, flash: { notice: "This is a flash message" },
  session: nil # Can safely be omitted.
 (called from block (3 levels) in <top (required)> at /[my_development_path]/login_required_lab-seattle-web-062419/spec/controllers/secrets_controller_spec.rb:13)"

**Comment by drakeltheryuujin** [comment]
Hi there,

It looks like this issue was flagged in the wrong repo, so I'm going to close it for now. If you can reopen this in the correct location, we will be happy to update the materials. Thanks for contributing!
